apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: cep
    component: esper
  name: cep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cep
        component: esper
    spec:
      containers:
      - name: cep
        image: gcr.io/iot-micros/cep:latest
