apiVersion: v1
kind: Service
metadata:
  name: cep
  labels:
    app: cep
    component: esper
spec:
  ports:
  - port: 8080
    name: cep-port
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: cep
    component: esper