apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka-entities
    component: consumer
  name: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-entities
        component: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/iot-micros/consumer:latest
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
