apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: front-end
    component: visual
  name: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
        component: visual
    spec:
      containers:
      - name: visual
        image: gcr.io/iot-micros/visual:latest
